//
//  ShowMovieInteractor.swift
//  Moviesapp
//
//  Created by Angel Betancourt on 6/18/18.
//  Copyright (c) 2018 Angel Betancourt. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowMovieBusinessLogic
{
  func doSomething(request: ShowMovie.Something.Request)
}

protocol ShowMovieDataStore
{
  //var name: String { get set }
}

class ShowMovieInteractor: ShowMovieBusinessLogic, ShowMovieDataStore
{
  var presenter: ShowMoviePresentationLogic?
  var worker: ShowMovieWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ShowMovie.Something.Request)
  {
    worker = ShowMovieWorker()
    worker?.doSomeWork()
    
    let response = ShowMovie.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
