//
//  ShowMovieModels.swift
//  Moviesapp
//
//  Created by Angel Betancourt on 6/18/18.
//  Copyright (c) 2018 Angel Betancourt. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ShowMovie
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
